### ISSUE TITLE
Dense crowds

### ISSUE THREAD

**Issue by evan-tan** [Shuijing725/CrowdNav_DSRNN#1]
Hi guys how do I replicate the environment shown in your video with the dense crowds in circular formation?

**Comment by Shuijing725** [comment]
Hi evan-tan,

In crowd_nav/configs/config.py, set ` sim.group_human = True` and change `sim.human_num` to a larger number for a denser crowd (we tried 10, 15, and 20 in our paper). 

Best,
Shuijing

**Comment by evan-tan** [comment]
Cool thank you! I managed to get it working.
