### ISSUE TITLE
There is no method named “set_policy()” in angent.py or human.py 

### ISSUE THREAD

**Issue by IOwenI** [Shuijing725/CrowdNav_DSRNN#10]
Hi，thank you for your sharing! But I find some problem in the project.
In crowd_sim.py， the method named "randomize_human_policies()" needs a method of human named "set_policy()" to randomize the moving humans' policies to be either orca or social force，but I can’t find any method named “set_policy()” in angent.py or human.py.  Maybe you didn't use it in your test so that you forgot it.

**Comment by Shuijing725** [comment]
Hi Wen.O,

Thank you for pointing it out! I just fixed it in the lastest commit [here](https://github.com/Shuijing725/CrowdNav_DSRNN/commit/16707af94d2649e5e29a877f7aac7b6f562fb80c). Please let me know if it still doesn't work.
