### ISSUE TITLE
Resume training from an existing checkpoint

### ISSUE THREAD

**Issue by IOwenI** [Shuijing725/CrowdNav_DSRNN#11]
Hi,I am very sorry to disturb you again.
I want to train from an existing checkpoint so I change the code in crowd_nav/configs/config.py as follow:
`training.resume = True  # resume training from an existing checkpoint or not`
`training.load_path = 'data/dummy/checkpoints/27776.pt'  # if resume = True, load from the following checkpoint`
But when I run train.py it shows error as follow:

>   File "/home/owen/文档/projects/CrowdNav/CrowdNav_DSRNN-main/CrowdNav_DSRNN-main/train.py", line 109, in main
>     actor_critic, _ = torch.load(load_path)
> ValueError: too many values to unpack (expected 2)

I change the code in train.py as:
`		torch.load(load_path)`
It run successfully.

**Comment by Shuijing725** [comment]
Thank you again for pointing it out :+1: ! I just pushed the fix.
