### ISSUE TITLE
How to run in real world? 

### ISSUE THREAD

**Issue by CAI23sbP** [Shuijing725/CrowdNav_DSRNN#18]
Hi, i read your paper and code. It was very interesting to me.

I have some question about running in real world.
In your paper, you used a camera for localization ( omit other camera).
But in your code ,there is just human position(px,py). 
How to connect localization and velocity control(v,w)?

Could am i looking forward to your answer. Thank you!

**Comment by Shuijing725** [comment]
See #13

**Comment by Shuijing725** [comment]
The sim2real tutorial is released here: https://github.com/Shuijing725/CrowdNav_Sim2Real_Turtlebot

**Comment by CAI23sbP** [comment]
Thank you!! @Shuijing725
