### ISSUE TITLE
Algorithm Problem

### ISSUE THREAD

**Issue by 2529342549** [Shuijing725/CrowdNav_DSRNN#19]
Hi,

I read your code. I have some questions about the code details.
When using the ST-RNN, the masks are input into GRU as a parameter. Could you explain why you did this? What is the function of masks input？

Thanks!

**Comment by Shuijing725** [comment]
Hi, 

The masks are the same as "done" in the gym environment. If an episode is done, we use masks to clear the hidden states of GRU to all zeros. See [this line].(https://github.com/Shuijing725/CrowdNav_DSRNN/blob/88f9209da0c1572489d9dfc25ceb3e5497bc2517/train.py#L177)
