### ISSUE TITLE
How to train CADRL ,RGL , LSTM_RL in this env?

### ISSUE THREAD

**Issue by CAI23sbP** [Shuijing725/CrowdNav_DSRNN#26]
How are you @Shuijing725 ?
I have a single question same as a title in this page.
In your paper, CADRL, RGL, LSTM-RL(compare with DSRNN) had been trained in this env(DS-RNN env)? 
If answer is yes, then how to training them in this env?

**Comment by Shuijing725** [comment]
You can do this by placing our gym environment code into the official repos of CADRL, RGL, and LSTM_RL. And leave everything else as it is.

**Comment by CAI23sbP** [comment]
Thank you
