### ISSUE TITLE
Unrecognized arguments

### ISSUE THREAD

**Issue by mincheulkim** [Shuijing725/CrowdNav_DSRNN#5]
Hi, I tried to run test.py with parser(e.g. --test_case, --test_model), but it can't be done because error with unrecognized arguments.

Its shown usage like below:(seems like from argument.py)
usage: test.py [-h] [--env_config ENV_CONFIG] [--output_dir OUTPUT_DIR]
               [--weights WEIGHTS] [--resume] [--load-path LOAD_PATH]
               [--overwrite] [--num_threads NUM_THREADS] [--phase PHASE]
               [--cuda-deterministic] [--no-cuda] [--seed SEED]
               [--num-processes NUM_PROCESSES]
               [--num-mini-batch NUM_MINI_BATCH] [--num-steps NUM_STEPS]
               [--recurrent-policy] [--ppo-epoch PPO_EPOCH]

**Comment by Shuijing725** [comment]
The argparse got confused with two set of arguments: `test_args` and `algo_args`. There might be a way to make it work with command line arguments, but the easiest workaround is to directly modify the arguments in the corresponding files and run `test.py` without command line arguments.

**Comment by mincheulkim** [comment]
Oh, ok. thanks.
There is another question about arguements.py
In line 9, '--env_config' is referencing 'crowd_nav/configs/env.config'. Should this be changed to 'crowd_nav/configs/config.py?

**Comment by Shuijing725** [comment]
Yes you are right. I just realized `--env_config` argument is never used anywhere. Deleting it from the code.
