### ISSUE TITLE
evaluation.py

### ISSUE THREAD

**Issue by evan-tan** [Shuijing725/CrowdNav_DSRNN#7]
Hi I was just wondering in `evaluation.py`, should it be `obs['robot_node'][0, 0, 0:2]` instead of `obs['robot_node'][0, 0, 1:3]` to get x,y position?  
Based off line 49 in crowd_sim_dict.py: `ob['robot_node'] = self.robot.get_full_state_list_noV()`

Also is `chc` the total change in heading for an episode?

**Comment by PeixinC** [comment]
Yes. Thanks for pointing it out. I have fixed the issue and updated the code.

**Comment by Shuijing725** [comment]
Yes, `chc` is the cumulative heading change of the robot in each episode.
