### ISSUE TITLE
2 agent scenarios

### ISSUE THREAD

**Issue by evan-tan** [Shuijing725/CrowdNav_DSRNN#8]
Hi I was wondering if it's possible to spawn a single human and a single robot for certain scenarios to evaluate side preference for passing, overtaking and crossing? I was trying to do that using the example model and it seems that the robot does well in approaching the goal but lingers around the last 0.5m of its goal. I've set `sim.human_num = 1` and spawned the robot and human directly opposite on a circle for passing.

**Comment by Shuijing725** [comment]
Yes, it is possible. You can just change the human number and starting & goal positions of each agent in the simulator.

It sounds like you are in the right direction, perhaps the model just needs more training or some hyperparameter tuning (including reward shaping) to get rid of the lingering behavior.

**Comment by evan-tan** [comment]
Thanks for the recommendation. Any idea which values I should start changing? I noticed that the difference between DSRNN and other papers is that DSRNN's reward function has much higher magnitudes.

**Comment by Shuijing725** [comment]
You can try things out and do experiments to test your hypothesis.
In fact, we could have normalized the reward to [-1, 1]. Feel free to try this.
